// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPS
{
        public const string achievement_collect_10000_paawos = "CgkIy775kbQREAIQBg"; // <GPGSID>
        public const string achievement_collect_100_paawos = "CgkIy775kbQREAIQBA"; // <GPGSID>
        public const string leaderboard_jumping_leaderboard = "CgkIy775kbQREAIQCQ"; // <GPGSID>
        public const string achievement_collect_1000_paawos = "CgkIy775kbQREAIQBQ"; // <GPGSID>
        public const string achievement_get_a_high_score_of_200_in_farm_mode = "CgkIy775kbQREAIQBw"; // <GPGSID>
        public const string leaderboard_leaderboard = "CgkIy775kbQREAIQAg"; // <GPGSID>
        public const string leaderboard_paawos = "CgkIy775kbQREAIQCA"; // <GPGSID>
        public const string achievement_login = "CgkIy775kbQREAIQAw"; // <GPGSID>
        public const string achievement_testachievement = "CgkIy775kbQREAIQAQ"; // <GPGSID>

}

