// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class PGPS
{
        public const string achievement_complete_level_10 = "CgkIy775kbQREAIQEQ"; // <GPGSID>
        public const string achievement_easter_egg_alert = "CgkIy775kbQREAIQFQ"; // <GPGSID>
        public const string leaderboard_jumping_leaderboard = "CgkIy775kbQREAIQCQ"; // <GPGSID>
        public const string achievement_complete_level_2 = "CgkIy775kbQREAIQAw"; // <GPGSID>
        public const string achievement_collect_100_paw = "CgkIy775kbQREAIQBA"; // <GPGSID>
        public const string achievement_thousandaire = "CgkIy775kbQREAIQBQ"; // <GPGSID>
        public const string achievement_bling_bling = "CgkIy775kbQREAIQFg"; // <GPGSID>
        public const string leaderboard_paw_leaderboard = "CgkIy775kbQREAIQGw"; // <GPGSID>
        public const string achievement_taaraekspert = "CgkIy775kbQREAIQFA"; // <GPGSID>
        public const string achievement_tenthousandaire = "CgkIy775kbQREAIQBg"; // <GPGSID>
        public const string achievement_bling_bling_vol_2 = "CgkIy775kbQREAIQFw"; // <GPGSID>
        public const string achievement_500_in_coins_mode = "CgkIy775kbQREAIQEg"; // <GPGSID>
        public const string achievement_complete_level_1 = "CgkIy775kbQREAIQAQ"; // <GPGSID>
        public const string achievement_get_a_high_score_of_200_in_coins_mode = "CgkIy775kbQREAIQBw"; // <GPGSID>
        public const string achievement_complete_level_3 = "CgkIy775kbQREAIQCg"; // <GPGSID>
        public const string achievement_complete_level_4 = "CgkIy775kbQREAIQCw"; // <GPGSID>
        public const string achievement_complete_level_5 = "CgkIy775kbQREAIQDA"; // <GPGSID>
        public const string achievement_complete_level_6 = "CgkIy775kbQREAIQDQ"; // <GPGSID>
        public const string achievement_complete_level_7 = "CgkIy775kbQREAIQDg"; // <GPGSID>
        public const string achievement_complete_level_8 = "CgkIy775kbQREAIQDw"; // <GPGSID>
        public const string achievement_complete_level_9 = "CgkIy775kbQREAIQEA"; // <GPGSID>
        public const string achievement_1000_in_coins_mode = "CgkIy775kbQREAIQEw"; // <GPGSID>

}

