// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "hR5DS1XgONhpJxwLAyLNO3yLjpBWqjZuJDyPP6jSlOXlenSn3I8mbnAjoH6XLlAIEGWiFM";
}
}
}

